
shape: sequence_diagram

client: "Client"
broker: "Broker"
server: "Server"

broker.class: brown

"subscribe(\"foo/bar\")": {
    server -> broker: "op: subscribe\ntopic: foo/bar/event-emission/any"
}

"emit(\"foo/bar\")": {
    client -> broker: "op: publish\ntopic: foo/bar/event-emission/any\ndata: Event-Emission"
    broker -> server: "op: publish\ntopic: foo/bar/event-emission/any\ndata: Event-Emission"
}

