
"Event Emission": {
    shape: sequence_diagram

    client: "Client"
    broker: "Broker"
    server: "Server"

    broker.class: brown

    "subscribe(\"foo/bar\")": {
        server -> broker: "subscribe\nfoo/bar/event-emission/any"
    }
    "emit(\"foo/bar\")": {
        client -> broker: "publish\nfoo/bar/event-emission/any\nEvent-Emission"
        broker -> server: "publish\nfoo/bar/event-emission/any\nEvent-Emission"
    }
}

