shape: sequence_diagram

client: "Client"
broker: "Broker"
server: "Server"

broker.class: brown

sink("foo/bar") {
    server -> broker: "op: subscribe\ntopic: foo/bar/sink-push-request/any"
}

push("foo/bar") {
    client -> broker: "op: subscribe\ntopic: foo/bar/sink-push-response/XXX"
    client -> broker: "op: publish\ntopic: foo/bar/sink-push-request/any\ndata: Sink-Push-Request"
    broker -> server: "op: publish\ntopic: foo/bar/sink-push-request/any\ndata: Sink-Push-Request"
    broker <- server: "op: publish\ntopic: foo/bar/sink-push-response/XXX\ndata: Sink-Push-Response"
    client <- broker: "op: publish\ntopic: foo/bar/sink-push-response/XXX\ndata: Sink-Push-Response"
    client -> broker: "op: publish\ntopic: foo/bar/sink-push-request/YYY\ndata: Sink-Push-Chunk #1 (first)"
    broker -> server: "op: publish\ntopic: foo/bar/sink-push-request/YYY\ndata: Sink-Push-Chunk #1 (first)"
    client -> broker: "op: publish\ntopic: foo/bar/sink-push-request/YYY\ndata: Sink-Push-Chunk #N (final)"
    broker -> server: "op: publish\ntopic: foo/bar/sink-push-request/YYY\ndata: Sink-Push-Chunk #N (final)"
    client -> broker: "op: unsubscribe\ntopic: foo/bar/sink-push-response/XXX"
}
