
shape: sequence_diagram

client: "Client"
broker: "Broker"
server: "Server"

broker.class: brown

register("foo/bar") {
    server -> broker: "op: subscribe\ntopic: foo/bar/service-call-request/any"
}

call("foo/bar") {
    client -> broker: "op: subscribe\ntopic: foo/bar/service-call-response/XXX"
    client -> broker: "op: publish\ntopic: foo/bar/service-call-request/any\ndata: Service-Call-Request"
    broker -> server: "op: publish\ntopic: foo/bar/service-call-request/any\ndata: Service-Call-Request"
    broker <- server: "op: publish\ntopic: foo/bar/service-call-response/XXX\ndata: Service-Call-Response"
    client <- broker: "op: publish\ntopic: foo/bar/service-call-response/XXX\ndata: Service-Call-Response"
}

