
vars: {
    d2-config: {
        layout-engine: elk
        theme-overrides: {
            N1:  "#303030"
	        N2:  "#606060"
	        N3:  "#909090"
	        N4:  "#c0c0c0"
	        N5:  "#e0e0e0"
	        N6:  "#f0f0f0"
	        N7:  "#ffffff"

            B1:  "#336699"
		    B2:  "#6699cc"
		    B3:  "#99ccff"
		    B4:  "#c0d0ff"
		    B5:  "#e0f0ff"
		    B6:  "#f0f8ff"

		    AA2: "#cfb098"
		    AA4: "#efd0b8"
		    AA5: "#ffe0c8"

		    AB4: "#efd0b8"
		    AB5: "#ffe0c8"
        }
    }
}


classes: {
    brown: {
        style: {
            fill:   "#ffe0c9"
            stroke: "#cfb098"
        }
    }
}

